CREATE TABLE `Hero`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `username` VARCHAR(50) NOT NULL,
    `hp` BIGINT NOT NULL,
    `atk` BIGINT NOT NULL,
    `def` BIGINT NOT NULL,
    `mana` BIGINT NULL,
    `rage` BIGINT NULL,
    `type` VARCHAR(50) NOT NULL
);
CREATE TABLE `monsters`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `Name` VARCHAR(50) NOT NULL,
    `hp` BIGINT NOT NULL,
    `atk` BIGINT NOT NULL,
    `def` BIGINT NOT NULL,
    `type` VARCHAR(50) NOT NULL
);